### PR TITLE
Create a retry and dlq strategy only to Topic and Direct exchanges 

### PR DESCRIPTION
**Pull request by andrelugomes**
Solving PR #11

### CODE REVIEW

**Comment by andrelugomes** [comment]
@juliofalbo new signed PR

**Comment by juliofalbo** [comment]
Hey man.

Can you create a Unit test for this modification?

You can use the file `https://github.com/Tradeshift/spring-rabbitmq-tuning/blob/master/src/test/java/com/tradeshift/amqp/rabbit/retry/QueueRetryComponentTest.java` and follow the exists tests.

Thanks!!

**Comment by andrelugomes** [comment]
@juliofalbo 

image

There is no coverage for this Bean. I'll think about some.

**Comment by andrelugomes** [comment]
@juliofalbo following your suggestion, we don't cover the configuration, because `QueueRetryComponentTest.java` only test the `retry and dlq` mechanism.

We need to verify if DLQ and RETRY queues haven't been created yet by `ConnectionFactory routingConnectionFactory` bean.

**Comment by juliofalbo** [comment]
> @juliofalbo following your suggestion, we don't cover the configuration, because `QueueRetryComponentTest.java` only test the `retry and dlq` mechanism.
> 
> We need to verify if DLQ and RETRY queues haven't been created yet by `ConnectionFactory routingConnectionFactory` bean.

True, you are right!
So, we need to create a test to cover these situations.

I'll work on it and create a PR with this tests, I'll follow your suggestion! (Do you want to do this?)

**Comment by andrelugomes** [comment]
Let me do! Don't worry.

**Comment by juliofalbo** [comment]
> Let me do! Don't worry.

Amazing! 🥇

**Comment by andrelugomes** [comment]
Hi @juliofalbo 

I extracted the declarations and bindings to a single responsibility class.

What you think?

**Comment by juliofalbo** [comment]
@wesleyegberto , Do you think is possible to use your strategy (Component Factory) with this strategy to create queues? I really liked both, and I see they working together!

**Comment by wesleyegberto** [comment]
Sure, we could centralize the creation of any component from RabbitMQ there.
[Here](https://github.com/wesleyegberto/spring-rabbitmq-tuning/blob/16961da67255d2f99a6712fb0e4e0dcc2686d075/src/test/java/com/tradeshift/amqp/autoconfigure/TunedRabbitAutoConfigurationTest.java#L511) I created a test to verify the creation of Exchange and Queues.

One thing that is missing is the test of binding between the exchange and queue, but I planning to continue on it to cover the following cases:

- DLQ and Retry enabled
- Only DLQ enabled
- Only Retry enabled
- One event with DLQ and Retry enabled and one event with DLQ and Retry disabled

**Pull request merged**
